[package]
version = "0.1.1"
authors = ["pegasos1"]
description = "Cargo subcommand to profile your applications."
homepage = "http://github.com/pegasos1/cargo-profiler"
repository = "http://github.com/pegasos1/cargo-profiler"
license = "Apache-2.0"
keywords = ["cargo", "profiler", "subcommand", "valgrind", "performance"]
name = "cargo-profiler"

[dependencies]
clap = "2.5.1"
regex = "0.1.69"
ndarray = "0.5.1"
lazy_static = "0.2.1"
rustc-serialize = "0.3"

[lib]
name="profiler"
lib="src/lib.rs"

[[bin]]
name = "cargo-profiler"
bin='src/main.rs'
